name: Build on NixOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Build with Nix
      run: | 
        nix --experimental-features "nix-command flakes" develop -c npm run build:release --if-present
        nix --experimental-features "nix-command flakes" develop -c cd Game/ldjam54 && npm run build:release --if-present
        cp index.* /var/www/ldjam56.rlyeh.nu/
        cp dist/* /var/www/ldjam56.rlyeh.nu/
