# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted # Use NixOS runner

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
    - run: nix --experimental-features "nix-command flakes" develop -c npm run build:release --if-present
    - run: nix --experimental-features "nix-command flakes" develop -c cd Game/ldjam54 && npm run build:release --if-present
    - run: cp index.* /var/www/ldjam56.rlyeh.nu/
    - run: cp dist/* /var/www/ldjam56.rlyeh.nu/

